version: 0.1.{build}-dev

shallow_clone: true

environment:
  LUAROCKS_VER: 2.4.1
  LUA_VER: 5.1.4

platform:
  - x86
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

# Skip unsupported combinations (ie, VS2008 for x64 is not supported)
init:
- if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )

install:
- git clone https://github.com/lidesdk/appveyor_lua.git .appveyor
# Make compiler command line tools available
- call .appveyor\set_compiler_env.bat
# Setup Lua development/build environment
- call .appveyor\install.bat

#before_build:
## @todo
#- echo "Installing external deps"

build_script:
  - luarocks install luafilesystem
  #- luarocks install https://raw.githubusercontent.com/lidesdk/framework/develop/lide-0.1-0.rockspec

test_script:
- echo "Testing..."
- set LIDE_PATH=%CD%
- dir .
- lua tests/lide_core_oop_tests.lua
- lua tests/lide_base_file_tests.lua
- lua tests/lide_core_error_tests.lua